# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8013aed4096deec6861692008b1f6a9fee42d4c63ce906a0bfa02a83c59abb14ce1b8035e135187cc1be4160c61f85a17f165b516eb3dd00109ded312241b5f4
  secret_access_key: ik8Hm8KZ9v883DKBc3ZR5DkmLK1Q2InWnaLigjHy
  stripe_secret_key:	sk_test_SBkfeEx6dIHOskvTvbNWCFqu
  stripe_publishable_key: pk_test_enVfdhhdSke46ITemj8GnHPp
  sendgrid_user:  traviagio
  sendgrid_password:  makers14

test:
  secret_key_base: 63bc27f729724dd2e80269d6e5059037f7d48637fa8bb303bbc3f7e06b0bd367f53b86f82d1c85ae3f857219fb9859cd7ea0db01330dfed5c709de6d5cc2223b
  secret_access_key: ik8Hm8KZ9v883DKBc3ZR5DkmLK1Q2InWnaLigjHy

production:
  secret_key_base: ab89b0b6b277082d6b4b396025ca7a34ba7b9a06603305b3d962abd032c6705f70aaf795628456e1ff5b0dee1c3cc606c3b0469630bd12fa2f41e92e16d9eb04
  secret_access_key: ik8Hm8KZ9v883DKBc3ZR5DkmLK1Q2InWnaLigjHy
